### ISSUE TITLE
Add Code Coverage to GitHub

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#105]
As part of the development, we regularly add tests to Poseidon. However, during code reviews, the code coverage is not clearly visible to developers and reviews. Thus, we would like to improve the visibility of the code coverage:

- [x] Add total coverage badge to ReadMe
- [x] Add total and diff coverage to Merge Requests
- [ ] Add a link to the coverage report from (already created in GitHub actions) to Merge Requests
- [ ] ~~Combine code coverage from unit tests and e2e tests~~

We might also consider using some external tool, such as CodeClimate or another marketplace plugin for these tasks.

**Comment by mpass99** [comment]
We had already been dealing with Task 4 for (too) long when we created the first e2e tests. It was a struggle. As far as I remember, one problem was that you can make a coverage report for the execution of tests; however, this doesn't help much with the e2e tests because they only interact indirectly with Poseidon via http requests. Thus, the coverage report would only include the e2e tests themselves. The struggle to find a solution to create a coverage report from Poseidon during the execution of the e2e tests was one that we gave up. Unfortunately, I can [hardly](https://gitlab.hpi.de/codeocean/codemoon/poseidon/-/merge_requests/23#note_135999) find any documentation of this.

**Comment by MrSerth** [comment]
Alright, thanks for adding these findings to the combined code coverage. I know how it works for Ruby, but if it is so much harder for Go, we just leave it out for now.
