### ISSUE TITLE
Create Grafana Dashboards

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#110]
As a follow-up to #67, we want to create Grafana statistics based on the data we collected. These dashboards should visualize the data and provide a quick overview of:
- a histogram of incoming requests
- status of a request (success / failure / HTTP code)
- insights on the usage of runners (creation, deletion, reusing)

**Comment by mpass99** [comment]
@MrSerth, I would appreciate it if you could set up the new data source in Grafana or give me the necessary permissions..

**Comment by mpass99** [comment]
@MrSerth, I would appreciate it if you could set up the new data source in Grafana or give me the necessary permissions..

**Comment by MrSerth** [comment]
> @MrSerth, I would appreciate it if you could set up the new data source in Grafana or give me the necessary permissions..

I've granted you additional permissions to proceed here (as I thought it is already configured -- both events are written to the same organization in Influx, just different buckets. In Grafana, there is a "default" bucket where I thought more access is possible. But maybe I restricted that when creating the token for the Grafana dashboard)

**Comment by mpass99** [comment]
Thanks! I guess the access from Grafana to InfluxDB was ok. The existing CodeOcean Data Source uses InfluxQL where "codeocean" was specified as database (/ bucket). Which is why the other buckets were isolated..
Speaking of which, now that we're already creating a new dashboard, we're also using the newer language, Flux, right?

**Comment by MrSerth** [comment]
Yes, using Flux is a good idea as we are creating a new dashboard anyway :)

**Comment by mpass99** [comment]
How about using "Grafana as code" [[1]](https://grafana.com/blog/2020/02/26/how-to-configure-grafana-as-code/)?

| Pro                                                                                                   | Contra                                                                                                                                                                                                                                                                             |
|-------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Version Control (Possible Rollback, Reviewing, Teamwork)                                              | This is a very young area [[2]](https://grafana.com/go/grafanaconline/2021/dashboards-as-code/). Many tools are still in the beta phase [[3]](https://github.com/weaveworks/grafanalib) [[4]](https://github.com/grafana/grafonnet-lib) [[5]](https://github.com/grafana/grizzly). |
| Otherwise, all users of Poseidon would always have to invest their own time in dashboard development. | It's extra work that pays off most when you have many dashboards and reuse colours, graphs or structures - but we only have one dashboard.                                                                                                                                         |
| Data visualisation in the same place as data collection.                                              |                                                                                                                                                                                                                                                                                    |

There are two variants:
- The Python library, grafanalib [[3]](https://github.com/weaveworks/grafanalib) [[6]](https://medium.com/@tarantool/grafana-as-code-b642cac9ae75)
  - More releases and stars
- The Jsonnet library, grafonnet-lib [[4]](https://github.com/grafana/grafonnet-lib)
  - Official Tool of Grafana

For automated deployment there is the official Grafana tool [Grizzly](https://github.com/grafana/grizzly).

What do you think?

**Comment by MrSerth** [comment]
Really good question and awesome overview!

Usually, I'm in favour in "as code" approaches as they provide easier reproducibility and allow version control. However, for Grafana, I tend to keep it simple. If you think we have great benefits with the "as code" approach, feel free to do so. Otherwise, I would "just" export the JSON definitions of the dashboard and copy that manually to the repo. Sure, that means both can diverge, but once the dashboard is done, it is not likely to change that dramatically.

**Comment by mpass99** [comment]
What are the open ToDo's here? Proposals:
- Save Runner Id for the execution monitoring in order to optimize the panel `Executions per runner`.
- Adjust the panel `Executions per minute` to use the new measurement.
- Adjust the panel `Runner per minute` to use the new measurement.
- Adjust the panel `Prewarming Poolsize and idle Runner` to use the new measurement.
- collect data to measure how long Nomad takes to start an allocation?
- Remove redundant bar charts
- Add gauge for current number of environments, used runners and executions.
-
