### ISSUE TITLE
Poseidon requires restart to send updated data to Influx

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#204]
We temporarily had a low availability of Runners. Afterwards, Poseidon does not send the most up-to-date data to Grafana, so that we have a discrepancy between the data returned by the API (for the current prewarming pool size) and the data written to Influx. After restarting Poseidon, the data reported automatically increased and was as expected.

<img width="940" alt="Bildschirmfoto 2022-08-27 um 00 10 09" src="https://user-images.githubusercontent.com/7300329/186997094-b29deab2-a906-42b2-96c6-9377c575c413.png">

**Comment by MrSerth** [comment]
[Poseidon-1H](https://sentry.io/organizations/openhpi/issues/3399850901/) might be related

**Comment by mpass99** [comment]
> [Poseidon-1H](https://sentry.io/organizations/openhpi/issues/3399850901/) might be related

The Sentry events seem to correlate with a high iowait cpu usage (25%) of the influx server (`telegraf-system-dashboard?from=1662156000000&to=1662242399000`). Unfortunately, this is not explaining this GitHub issue as the cpu usage on the date of the screenshot is normal (also there are only seven Sentry events).

**Comment by MrSerth** [comment]
We are currently facing issues with some timeouts in our cloud, so I wouldn’t take those timeout information for granted. 

Updating and restarting Nomad also yielded the Influx alert today, even though everything was fine. Restarting Poseidon fixed it.

**Comment by mpass99** [comment]
> Updating and restarting Nomad also yielded the Influx alert today, even though everything was fine. Restarting Poseidon fixed it.

Good hint! My assumption that is creating the same behavior:

Here,
https://github.com/openHPI/poseidon/blob/e8457ca035d57b34d848e935913b38a24ec97052/internal/runner/nomad_manager.go#L120-L129
we keep track of new runners by an event stream. If the event stream fails we try again with an error log. After a Nomad restart, Poseidon still creates a new runner for a provided one but it does not add it to the idle runners. I assume that is because the event stream is broken and does not notify Poseidon about the new runner.

Site notes:
- There is no error message telling that the event stream will be retried.
- The event stream is broken with Nomad restarting, but not with a short lost of the (VPN) connection.
- The behavior is matching the time of the screenshot: No new runner started but with every new user one less idle runner.
- Poseidon restart fixes this because the event stream is recreated.

**Comment by MrSerth** [comment]
We're still facing this issue 😒
