### ISSUE TITLE
Design and implement statistical route about pool size

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#24]
As an administrator on CodeOcean  
I would like to get an overview of allocations/runner currently used or prewarmed
in order to get an impression of the overall system load.

<hr>

On CodeOcean, we have some statistics for each execution environment. We should design an API and implement it in Poseidon (and DCP afterward) to provide the information required. I assume the following information is useful per execution environment:

- Desired pre-warming pool size 
- Actual pre-warming pool size 
- Used runner pool size (as reserved for specific users and not available for new users)

This is how it the dashboard looks like right now (not all information included yet):

<img width="1142" alt="Bildschirmfoto 2021-11-01 um 14 07 43" src="https://user-images.githubusercontent.com/7300329/139676385-9f93a37e-99e3-4306-87bf-1dd9671f6c33.png">

**Comment by MrSerth** [comment]
We might consider adding the information about runners currently in use to the `/execution_environments` routes. They already contain most information and would only need one or two additional attribute(s).

**Comment by mpass99** [comment]
I have a small problem with maintaining modularity. The information about the requested and actual size of the prewarming pool is in the Execution Environment. However, the number of runners currently in use is in the Runner Manager. Since an Execution Environment so far knows itself how to turn into JSON, we can only add very hacky attributes afterwards.
Therefore, I would suggest that we create an extra GET `/execution_environments/statistics` (?) route that only returns the three attributes `prewarmingPoolSize`, `idleRunners` and `usedRunners`. This way we have one more route, but we have avoided the modularity problem and even simplified the responses (the dashboard only needs these three attributes, while CodeOcean does not need them).
What do you think of that? I could also look for another solution without an additional route...

**Comment by MrSerth** [comment]
Sure, I am fine with introducing a dedicated route to gather statistical information. The attributes sound reasonable and would cover the intended use case. I am just wondering whether we should use the path `/execution_environments/statistics`. This would potentially behave incorrectly if (for whatever reason) an execution environment gets created with the ID `statistics`. What if we swap both components and name it `/statistics /execution_environments`. That would also allow for future extensibility with other statistical information, e.g., regarding the number of open connections or other usage-related information.

**Comment by mpass99** [comment]
Very good point!
