### ISSUE TITLE
Playbook for Dashboard Deployment

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#255]
See #245 and #110 

- Fetch the current environments from Poseidon and writes the `environments.json` file
  - May be implemented via an Ansible playbook
- Generates and deploys the current dashboard
  - [Grizzly](https://grafana.github.io/grizzly/) may be useful

**Comment by mpass99** [comment]
From the Issue description, I assume that it is out of scope of this issue to have an influx and Grafana (Terraform) provisioning?!

**Comment by MrSerth** [comment]
Mh. Technically, I would say so. However, we probably need that in order to tackle this issue. Let's see whether I can start with a template...

**Comment by MrSerth** [comment]
I started with the required Terraform files and some basic Ansible script that installs the required dependencies. A PR is in our GitLab next to yours 🙂

**Comment by MrSerth** [comment]
Grizzly might be a good solution and I like to have some wraper for the API. What if we try to base the Ansible playbook on https://github.com/ansible-collections/community.grafana? Some parts might work pretty well (such as synchronizing dashboards) and others (such as defining the datasources) might be a bit more difficult. One advantage I see is the better integration with Ansible instead of "just" executing a CLI tool. However, for some use cases it doesn't work nicely with Ansible and using a CLI tool is required (such as I did for Influx).

**Comment by mpass99** [comment]
Yeah, I like the use of the Ansible Collection! It is easy to use and has more documentation that Grizzly.
Why do you prefer the community version? I have a slight preference to [the official collection](https://docs.ansible.com/ansible/devel/collections/grafana/grafana/index.html) as we can then structure the definitions in template files (as I got them now) and not directly in the Ansible rules..

**Comment by mpass99** [comment]
Good Point! With the community version it seemed more complicated on the first look. On the second look, this complexity is introduced by parameters such as the authentication which is required for our use case :ok_hand: 
I'm not completely finished with my part but have a general understanding. If you want, we can finish it tomorrow together?!
