### ISSUE TITLE
Systemd Socket

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#473]
Related to #465

Configure a systemd socket that receives and forwards all traffic to Poseidon
in order to prepare a graceful restart.

**Comment by mpass99** [comment]
@MrSerth You've already implemented this for CodeOcean, right? Could you please link the implementation for inspiration? :)

**Comment by MrSerth** [comment]
I am mainly using the socket activation scheme from CodeOcean's web server, which is Puma. That web server has a [short documentation](https://github.com/puma/puma/blob/master/docs/systemd.md#socket-activation) on the socket activation. Otherwise, our staging environment also has a current replica of the production config:

- `/etc/systemd/system/codeocean.service`
- `/etc/systemd/system/codeocean.socket`

Within CodeOcean, I am just instructing my web server to [bind to the activated sockets only](https://github.com/openHPI/codeocean/blob/cee3ceb188c9a954fbad398ab1ba1beb7880612e/config/puma.rb#L49-L51). Therefore, it was somewhat simple to add the systemd socket to CodeOcean 😉.
