### ISSUE TITLE
Monitor Nginx Access Log

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#608]
In issues #428 and #591, we stumbled over rejected requests in our Nginx access logs. To cover this visibility issue, let's configure Telegraf to monitor the Nginx access log.

We already have a Grafana dashboard that tries to access the Telegraf Nginx access log data in Influxdb and currently fails.

**Comment by mpass99** [comment]
Related to #437 and #471

**Comment by MrSerth** [comment]
We recently fixed all Grafana dashboards, and also switched to an updated version of the previous Nginx dashboard used: https://grafana.com/grafana/dashboards/21987-nginx-metrics/

This dashboard not only shows the nginx request information, but also reports the status code of handled requests. Hence, it allows us to discover requests with a too large payload.

We are still lacking the Loki stack and monitoring for other system services. However, since we have a dedicated ticket for them, I am closing this issue.
