### ISSUE TITLE
Error loading runner portMappings in Sentry context

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#628]
Despite running code successfully, the sentry context is not set correctly [[see this example]](https://codeocean.sentry.io/performance/trace/19666d3dc5ab4091a14f4313571a891c/?node=span-540302fc41015b80&node=txn-b6ceb102e7dd4486b6b88c5147376765&node=txn-9db02d0981b8470cbeb65342cd916540):

```
error loading runner portMappings: error querying allocation for runner 29-c8c06eee-381c-11ef-bc48-fa163e1390db: no allocation found
```

<img width="1374" alt="Bildschirmfoto 2024-07-08 um 10 27 18" src="https://github.com/openHPI/poseidon/assets/7300329/951418cb-2d33-4aa3-820a-556c1536e930">

We should investigate how this could happen and fix the underlying issue.

**Comment by mpass99** [comment]
In the context of #643, we have found the underlying issue of this behavior.

It is caused by our Sentry hook modifying either the global or the request-based scope.

https://github.com/openHPI/poseidon/blob/4ec8aaaf18f2aadf0034599338d7a73a770d14d9/pkg/logging/sentry_hook.go#L25-L33

When checking [recent traces](https://codeocean.sentry.io/performance/trace/3768552ee1054b2f85044dd223a2b1eb), we find that all have the error `synchronize runners failed: nomad Event Stream failed!: error receiving events: unexpected EOF` attached even if the [last occurrence of it](https://codeocean.sentry.io/issues/4584430575/events/7236bb557cfe48ca8436b603ca0d8f70) was four days before.

This is because the context attached to this error has no request-based scope attached, so the global one is used. In this case, the scope was not cleared for multiple days.

We will fix this issue by using [Local Scopes](https://docs.sentry.io/platforms/go/enriching-events/scopes/#using-with-scope)

**Comment by MrSerth** [comment]
Sounds plausible, thank you. Let's merge (and deploy) the changes from #647 and observe the situation.
